name: Integration tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-docker:
    name: Ensure Docker image builds
    env:
      GITHUB_TOKEN: "tet123123"
      GITLAB_TOKEN: "asdfasdfasdF"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: Build Docker image
        run: |
          DOCKER_PUSH=false make image
